### ISSUE TITLE
Fatal error on /tags/id/[tag_id]

### ISSUE THREAD

**Issue by ldargent** [netgen/TagsBundle#76] opened 2018-06-15 06:51 UTC
eZDemoBundle is used for default configuration pagelayout.
Of course this bundle is not into composer dependencies.

This generate a twig fatal error :

`There are no registered paths for namespace "eZDemo".`

https://github.com/netgen/TagsBundle/blob/53f8d681fa5375a0760fb7f6c7f8db1ec8fb8675/bundle/Resources/config/default_settings.yml#L25

You should change it to avoid this error after clean install.
Or maybe specify into install.md that this parameter needs to be override ?

**Comment by emodric** [comment] 2018-06-15 08:47
Hi @ldargent 

Do you have a suggestion on a better default value? I used that one specifically because it will force users to actually change the default when they encounter the error.

**Comment by ldargent** [comment] 2018-06-15 09:05
Hi @emodric,

Ok I understand.

Maybe add a basic pagelayout (to avoid error) into the bundle and add documentation for "how to override pagelayout" or something like this ?

**Comment by emodric** [comment] 2018-06-15 09:48
Sure, why not. Wanna take a shot at it yourself? :)

**Comment by kbohutinski** [comment] 2018-12-14 00:02
hi, how to override this parameter?
Tnx

**Comment by emodric** [comment] 2018-12-14 13:46
@kbohutinski There's a `eztags.default.pagelayout` parameter that you need to set to override pagelayout.

**Comment by kbohutinski** [comment] 2018-12-15 22:33
@emodric 

I made override template view.html.twig and solved the problem.

In the Resources folder I added the file NetgenTagsBundle/views/tag/view.html.twig to which I wrote my source code.

But the biggest problem is that there is no tutorial on how to use netgen tags bundle or I did not find it.

The eztags.default.pagelayout parameter does not exist in my project when I do the search ?!

**Comment by emodric** [comment] 2018-12-19 11:50
@kbohutinski That's one way of overriding :)

Sorry about the wrong parameter name: it's name is `eztags.default.tag_view.pagelayout`.

There is indeed no tutorial yet :fearful: Is there a specific thing you need help with?

**Comment by kbohutinski** [comment] 2018-12-19 23:55
Not for now. But instructions are essential for such an important bundle. So if I have a problem I have to wait for you or I have to investigate.

BR

**Comment by emodric** [comment] 2018-12-20 16:18
I understand and I'm aware that the docs are lacking for the bundle. I do hope this will improve, though! Any contribution is welcome, too :)

**Comment by amauryvallier** [comment] 2019-02-01 14:49
Hello!

This issue seems important to me, since when a contributor clicks on a tag in a content on the content/media tree part, he will automatically be redirected to the /tags/view/[tag_name] url and get this error if the eZDemo is not installed.

Could it be possible to simply link to the admin interface of the tag (/tags/admin/tag/[tag_id]) for this display which will at least not break everything everytime but just sometimes when the user does not have the corresponding rights?

If it seems a good idea to you, I can try and propose a PR for that... but I don't know this bundle enough to judge if this is a good idea.

**Comment by emodric** [comment] 2019-02-04 14:08
@amauryvallier How about we use `ezpublish.configResolver.parameter('pagelayout')` ? It will resolve to whatever layout is configured in eZ. This custom config comes from the time where there was no central pagelayout param in eZ. We can deprecate it and switch to using the `pagelayout` param from eZ.

**Comment by amauryvallier** [comment] 2019-02-04 15:01
That could already be a better solution than having a brutal error page in the admin interface. The real problem to me is that we have this big error in the admin while using the bundle.

By changing the href on the `Resources/views/eztags_content_field.html.twig` file from `path( tag )` to `path('netgen_tags_admin_tag_show', {'tagId': tag.mainTagId})`, we can avoid the bug altogether in the admin interface. And in front, the user is directed to the login form unless he overrides the rendering of the tag field. Could it be a viable solution?

Even better would be having a specific admin override for this display/link. I don't even know if it is a possibility however. I'm still trying to wrap my head around it.

**Comment by emodric** [comment] 2019-02-06 11:43
> Even better would be having a specific admin override for this display/link. I don't even know if it is a possibility however. I'm still trying to wrap my head around it.

This should be possible. See `bundle/Resources/config/ezplatform.yml` file. If you wish to test, you can add a specific template here for `admin_group` scope. However, this is not a bulletproof solution. Every new siteaccess (for example, customer specific admin panels) or custom panels that integrate with Tags Bundle, should need to add such a config, but that is a trivial fix, so maybe not a real issue.

**Comment by amauryvallier** [comment] 2019-02-07 08:54
The idea would be to keep the global override as it is (and then we'll have the bug in front, which is the way that was intended so that everyone does its own thing here) and add a specific override for the admin_group that will avoid the BO error. So by defining two different overrides directly there we should be able to make it work!

I'll propose a Pull Request for this as soon as I can.

**Comment by emodric** [comment] 2019-02-07 09:06
> and then we'll have the bug in front, which is the way that was intended so that everyone does its own thing here

This can also be solved by using `ezpublish.configResolver.parameter('pagelayout')` as mentioned before. That way, 99% of installations will work out of the box.

**Comment by amauryvallier** [comment] 2019-02-07 10:14
I made a pull request integrating the better from both solutions (or so I hope)!

**Comment by emodric** [comment] 2019-04-02 17:28
Fixed with 7f2efd6e3eb555337c21cf1176353194b4a1964a

**Closed by emodric** 2019-04-02 17:28 UTC
