### ISSUE TITLE
Admin ui ezdesign changes.

### ISSUE THREAD

**Issue by wizhippo** [netgen/TagsBundle#77] opened 2018-06-20 19:07 UTC
Not sure if related to the switch to ezdesign in admin ui but I now get

Cannot find 'eztags_field' template block.

If I add the field templates to the admin group it works again without issue.

**Comment by emodric** [comment] 2018-06-20 20:00
Does it work if you disable standard design bundle?

Ref: https://github.com/ezsystems/ezplatform-standard-design/pull/2#discussion_r190838120

**Comment by wizhippo** [comment] 2018-06-20 20:09
It does work if standard design bundle is disabled

**Comment by emodric** [comment] 2018-06-20 20:16
> It does work if standard design bundle is disabled

I presume this is without adding the template to `admin` group?

Truth to be told, I'm not sure how to proceed here. The field template is in the `default` group, it should be enough for the fallback to work, right? I don't know what happens behind the scenes now that the standard bundle goes and creates a mess out of the templates entirely, so some kind of clear docs is definitelly needed, before I even begin to guess how to approach this :(

**Comment by emodric** [comment] 2018-06-20 20:33
Yes, I think it has the same effect as disabling the bundle itself. I still don't feel that it is a proper fix, however.

**Comment by wizhippo** [comment] 2018-06-20 20:34
Is there a reason the netgen templates are added with a priority of 0?  I just changed them to a priority of 99 and it's working?

**Comment by emodric** [comment] 2018-06-20 20:46
To answer, priority 0 is to enable 3rd party bundle to easier override the template by specifying their own priority.

**Comment by flutchman** [comment] 2018-07-18 13:57
Hello guys.

Just tried to update one project and got the same error as @wizhippo mentionned. Would there is by any chance a new fix that appeared other than commenting "ez_platform_standard_design" ? 

Thank you in advance :)

**Comment by emodric** [comment] 2018-07-18 14:04
@flutchman I don't know how to fix this. The templates need to be in `default` scope to allow using them in every area, and not to limit them to admin ui only.

I think this is something that needs to be fixed / documented on eZ side.

**Comment by andrerom** [comment] 2018-07-18 14:07
@alongosz / @damianz5 Any takes on what will be needed to avoid this issue from standard design?

**Comment by pbek** [comment] 2018-08-21 06:37
Just a little report, I still get this error when viewing tags in a location on the admin page in the current eZ Platform 2.2.

**Comment by alongosz** [comment] 2018-10-12 09:55
Hello. Sorry for the long delay. I was able to confirm this issue and found root cause of it in the Standard Design package. Reported as [EZP-29724](https://jira.ez.no/browse/EZP-29724), follow it to see the progress on that.
// cc @andrerom

**Comment by emodric** [comment] 2019-04-02 15:00
@wizhippo @pbek @raupie @flutchman Hi guys! Can anyone of you confirm that 600fea556edd5d8799457dfb391564136c2de725 fixes this issue?

**Comment by wizhippo** [comment] 2019-04-02 15:36
@emodric Working here now with `override_kernel_templates` left as true and not having to redefine `field_templates`

**Comment by emodric** [comment] 2019-04-02 15:37
Thanks!

Closing as fixed :)

**Closed by emodric** 2019-04-02 15:37 UTC
