### ISSUE TITLE
Tags input disappears after changing language while creating content

### ISSUE THREAD

**Issue by konradoboza** [netgen/TagsBundle#72] opened 2018-02-09 08:58 UTC
Good morning!

Currently, a new issue has been observed: while creating new content, changing its language causes disappearing of tags input. I reproduced this issue on eZ Platform 1.13 and tagsbundle v3.1.4.

![disappearing_tags_input](https://user-images.githubusercontent.com/34310128/36019473-b4ee7138-0d7f-11e8-8c9d-8e731e116fd1.png)

Please let me know if you could fix this.

Best regards

**Comment by emodric** [comment] 2018-02-12 16:34
Hi @konradoboza

Thanks, I will look into this soon, but I don't know if I can fix this, since YUI is not my strongest suit. I would appreciate if you could take a look at it too if you know where and how to fix it :)

**Comment by konradoboza** [comment] 2018-03-08 14:27
Hi @emodric,

I looked into this issue and found out, that there is a problem with rendering `templates.skeleton` template. After changing the language of the content it is somehow removed, but I couldn't reach the code which is responsible for that. Is it any possibility, that this is also used somewhere in the tags admin panel as this skeleton contains html code for autocomplete input? Maybe there is some wrong event which is triggered. Please take a look and give me any clues, so I'll be able to further investigate this problem.

**Comment by emodric** [comment] 2018-03-08 14:39
I can say with certainty that it's not used in admin panel, only for the field input. Why it dissapears, I cannot say, but I'll try to debug it!

**Comment by emodric** [comment] 2018-03-09 08:44
Hi @konradoboza 

I've tried testing the input with changing the language and I'm afraid I cannot reproduce your issue.

When I switch to another language in content edit interface, everything keeps on working as before, no issues whatsoever.

**Comment by konradoboza** [comment] 2018-03-09 08:57
I was able to reproduce it every time on a clean installation of eZ Platform v.1.13.0 with TagsBundle v3.1.4. Here are my steps to reproduce:

1. Add new language via admin panel and add it to `ezplatform.yml`
2. Clear cache and reload Platform UI.
3. Install TagsBundle 3.1.4 using instructions from its github page.
4. Add tags field to existing content e.g. "Article".
5. Create a new article.
6. Before publishing it, change the language.
*Result:* Tags field disappears.

Please let me know if you performed some similar tests. Which browser do you use?

**Comment by emodric** [comment] 2018-03-19 09:19
I reproduced the issue, and it seems that there is something missing somewhere which would reinitialize the interface on language change.

Simply calling `jQuery('#eztagsXYZ').EzTags();` from the console (XYZ is the field def ID of the tags field) makes the interface reappear, which indicates that all we need is an initializer method which would execute on language change. I hope you know a place where we can stick that initialization :)

**Comment by konradoboza** [comment] 2018-03-22 13:08
I tried to fix it the way you suggested, but it won't work. When I reinitialize the interface by using `jQuery('#eztags123')` it corrupts the popup for selecting tags from the tree. See screenshot below.

![select_tag_issue](https://user-images.githubusercontent.com/34310128/37771502-1072bd02-2dd8-11e8-8f18-e976ae6b3816.png)

Maybe re-rendering whole Tags template and re-attach all events could be a possible workaround? If yes, please give me some clues how to do it properly and I could try to put it in a correct place.

**Comment by konradoboza** [comment] 2018-04-03 12:28
@emodric do you maybe have any feedback regarding this issue?

**Comment by emodric** [comment] 2018-04-03 12:55
Unfortunatelly not. I tried debugging it further, but it goes beyond by YUI/JavaScript knowledge, so if you could try and fix it by yourself, it would be very much appreciated.

**Comment by emodric** [comment] 2021-07-14 09:15
Closing as obsolete.

**Closed by emodric** 2021-07-14 09:15 UTC
Labels: bug, wontfix
