### ISSUE TITLE
Ibexa 4.2 : Bug after creating first tag, on tag show action

### ISSUE THREAD

**Issue by plesigne** [netgen/TagsBundle#153] opened 2022-10-18 14:50 UTC
On tag 5.0.2

When creating a tag, if no content type has an eztag field, there is this error:

`Argument '$criterion->target' is invalid : No searchable fields found for the given criterion target '
`
Error is thrown in vendor/netgen/tagsbundle/bundle/Core/Search/Solr/Query/Common/CriterionVisitor/Tags/TagId.php line 28.

It is therefore necessary to add an eztag field to a content before the creation of keywords so that the creation of the tag does not fail.

**Comment by emodric** [comment] 2022-10-19 14:51
Hi @plesigne !

Thanks for reporting this issue. I have reproduced it, however, this is not easily fixed.

The exception you're getting is actually present by design, to let you know that you can't use `TagId` and `TagKeyword` criteria unless you add some `eztags` fields to your content types.

However, Tags admin interface uses the same criteria to show content related to a specific tag, and this ofcourse requires that at least one `eztags` field is present in your content types. This is basically a chicken & egg situation, so there is no real solution.

You will have to add an `eztags` field to your content before adding any tags OR you can switch to legacy search engine where this issue is not present.

I will go ahead and close this issue since there is no real solution we can implement.

If you think of a solution that we can use here, feel free to create a new issue and/or pull request.

Thanks!

**Closed by emodric** 2022-10-19 14:51 UTC
