### ISSUE TITLE
Add new tag button visibility issue

### ISSUE THREAD

**Issue by konradoboza** [netgen/TagsBundle#69] opened 2017-12-22 13:03 UTC
Hello!

In eZ Platform 1.12 there is a problem with adding tags to the content (it appears on Safari, Chrome and Firefox).

**Steps to reproduce**
1. Open new incognito tab.
2. Log in to the eZ back office using PlatformUI.
3. Create new content (e.g. an article) or select existing one.
4. Go to the tag sections. "Add new" button is not visible.

![no_button](https://user-images.githubusercontent.com/34310128/34298786-c519d6dc-e71f-11e7-8cf5-d1a54d02b16c.png)

After reloading page, everything seems to be working.

I did some debugging and I manage to figure out, that it might be some issue with flag "hasAddAccess" inside an jQuery.eztags.js extension. I hope it might be helpful.

Please let me know if you could fix this.

Best regards

**Comment by emodric** [comment] 2017-12-22 13:06
@konradoboza Thanks for reporting it!

Are you use your users have the `tags/add` policy? Which version of the bundle are you using?

**Comment by konradoboza** [comment] 2017-12-22 13:11
@emodric thank you for quick reply!

I reproduced it on Administrator user, so I had all permissions. Just to be sure, I added also `tags/add` policy. I'm using version `3.1.4` of `netgen/tagsbundle`.

**Comment by emodric** [comment] 2017-12-22 13:14
Thanks! I'll try to reproduce it locally!

**Comment by emodric** [comment] 2017-12-22 13:40
I've reproduced the issue. The issue comes from the fact that tags bundle config, including "has add access" flag, is fetched from config provider: https://github.com/netgen/TagsBundle/blob/master/bundle/PlatformUI/ConfigProvider.php#L51, which is obviously loaded only once, when login page is displayed, and is not reloaded when the user is logged in.

Truth to be told, I'm not really sure how to fix this, since loading this configuration is outside my control and there's no other way for me to check if user has access.

Would it be possible to report the issue to eZ Systems so they can try and fix it?

**Comment by konradoboza** [comment] 2018-01-16 08:27
PR with suggested workaround: https://github.com/netgen/TagsBundle/pull/71

**Comment by emodric** [comment] 2018-01-17 16:19
Fixed by #71

**Closed by emodric** 2018-01-17 16:19 UTC
Labels: bug
